# Site settings
title: Adam Tew
email: adamjtew@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Adam Tew
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://adamtew.com/" # the base hostname & protocol for your site
twitter_username: adamjtew
github_username:  adamtew

# Build settings
markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
